# Create a new user
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.local",
  "userName": "Keks",
  "password": "123456"
}

###

# Получение детальной информации о пользователе по ID
GET http://localhost:4000/api/auth/679460f25fc500c3a623235f HTTP/1.1


###

# Login user by email and password
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user3@notfound.local",
  "password": "12345"
}

###


# Get new JWT pair
POST http://localhost:4000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0NjBmMjVmYzUwMGMzYTYyMzIzNWYiLCJlbWFpbCI6InVzZXI3QG5vdGZvdW5kLmxvY2FsIiwidXNlck5hbWUiOiJLZWtzIiwidG9rZW5JZCI6IjU3MzQ0NjE0LThkZTQtNGRhYy05Mjg2LWMzM2ExZWU1ZmJkMSIsImlhdCI6MTczNzk0OTYyNSwiZXhwIjoxNzQwNTQxNjI1fQ.YeqRWUSVQgdXvzOJ5dYIf8ko61y3nOUNwhpxFy1sqYA
###


# Check user token
POST http://localhost:4000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0NjBmMjVmYzUwMGMzYTYyMzIzNWYiLCJlbWFpbCI6InVzZXI3QG5vdGZvdW5kLmxvY2FsIiwidXNlck5hbWUiOiJLZWtzIiwiaWF0IjoxNzM4MDM3OTM2LCJleHAiOjE3MzgwMzgyMzZ9.Fje72EoNEKcyjllGRZmuUiNVqRe3I8bDEXdxj-quIdM

###


# Change user password
POST http://localhost:4000/api/auth/changepassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzVlZWFjMDU2N2I5ZjhlNzMzMTAyY2UiLCJlbWFpbCI6InVzZXIzQG5vdGZvdW5kLmxvY2FsIiwidXNlck5hbWUiOiJLZWtzIiwiaWF0IjoxNzM4NDczNTY1LCJleHAiOjE3Mzg0NzM4NjV9.voOh9kjiJjtV8CsfpHcbfOr1gn8-R8vOIJtM6HKT3AM
{
  "email": "user3@notfound.local",
  "password": "123456",
  "newPassword": "12345"
}

###
