# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "firstname": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/47098f01-a7bb-48ec-9010-1ba80979593e HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
