# Получить все публикации
GET http://localhost:3000/api/posts HTTP/1.1

###

# Получить публикации с сортировкой и фильтрацией
//фильтрация по тегам (teg=), по заголовке (name=) - (достаточно содержания одного слова),
//по userId =
//сортировка по дате создания, количеству лайков, количеству комментариев sortType=countLikes|countComments|createdAt
//напрвление сортировки sortDirection=decs|asc
GET http://localhost:3000/api/posts? HTTP/1.1

###

# Получить публикацию по id (просмотр детальной информации)

GET http://localhost:3000/api/posts/54276374-5ea4-4fb0-851e-a16d83d60516 HTTP/1.1

###

# Создать публикацию
# Типы публикаций (type) - video|text|quote|foto|reference
# Состояние публикаций (state) - draft|published
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "tegs":[],
  "userId":"6755746b5903856268a55d4b",
  "state":"published",
  "repost":false,
  "type":"text",
  "name": "Животные 2 часть. Изучаем фауну Северной и Южной Америки"

}

###


# Создать репост публикации с определенным id пользователем с userId
POST http://localhost:3000/api/posts/repost/ccfac116-0fdc-427b-ba9b-d08eeb2313dc HTTP/1.1
Content-Type: application/json
{
  "userId":"6755746b5903856268a55d4a"
}

###

# Удалить публикацию по id

DELETE http://localhost:3000/api/posts/246aed1a-3f23-4191-966c-71cedcd62366 HTTP/1.1

###

# Обновить публикацию по id

PATCH http://localhost:3000/api/posts/adba5e4c-6388-4c93-90ad-a6e249194790 HTTP/1.1
Content-Type: application/json

{
  "state": "draft"
}


