# Get all posts
GET http://localhost:3000/api/posts HTTP/1.1

###

# Get posts with filter

GET http://localhost:3000/api/posts?limit=2&sortDirection=desc&state=draft HTTP/1.1

###


# Get post by Id

GET http://localhost:3000/api/posts/a491c6cf-14d5-42b9-8fa6-29991d7dd5b1 HTTP/1.1

###

# Create a new post

POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "tegs":[],
  "userId":"6755746b5903856268a55d4a",
  "state":"draft",
  "repost":false,
  "type":"text",
  "name": "Космос 4 часть",
  "video":"",
  "announcement":"",
   "text":"",
  "author":""

}

###

# Delete a post by id

DELETE http://localhost:3000/api/posts/3ee2cc3b-81cc-4789-bb50-d20b73ec2c34 HTTP/1.1

###

# Update a post by id

PATCH http://localhost:3000/api/posts/a491c6cf-14d5-42b9-8fa6-29991d7dd5b1 HTTP/1.1
Content-Type: application/json

{
  "name": "This is new title"
}

###
# Create a new comment for post
POST http://localhost:3000/api/posts/a491c6cf-14d5-42b9-8fa6-29991d7dd5b1/comments HTTP/1.1
Content-Type: application/json

{
  "message": "This is text3",
  "userId": "65990102bb965b742900ba59"
}
