
# Поставить лайк для публикации (postId в аргументе)
POST http://localhost:3000/api/posts/likes/246aed1a-3f23-4191-966c-71cedcd62366 HTTP/1.1
Content-Type: application/json

###

###
# Удалить лайк для публикации (postId в аргументе)
DELETE http://localhost:3000/api/posts/likes/246aed1a-3f23-4191-966c-71cedcd62366 HTTP/1.1
Content-Type: application/json


